steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/summer-nexus-468907-t1/my-jenkins-repo/jenkins-app:$COMMIT_SHA', '.']

# Step 2: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/summer-nexus-468907-t1/my-jenkins-repo/jenkins-app:$COMMIT_SHA']

# Step 3: Apply manifests (deployment + service)
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

# Step 4: Update image in Kubernetes deployment (forces rollout)
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/myapp-deployment
    - myapp=us-central1-docker.pkg.dev/summer-nexus-468907-t1/my-jenkins-repo/jenkins-app:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

# Images section
images:
- 'us-central1-docker.pkg.dev/summer-nexus-468907-t1/my-jenkins-repo/jenkins-app:$COMMIT_SHA'

# ✅ Use Cloud Logging only (no GCS bucket needed)
options:
  logging: CLOUD_LOGGING_ONLY
